version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: django
    versions:
    - "3.1"
  - dependency-name: flake8
    versions:
    - 3.8.0
